apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"

# kubectl taint nodes node1 app=blue:NoSchedule