apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
  annotations:
    buildversion: 1.34
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
        - name: busybox
          image: busybox

# kubectl replace -f replicaset_definition.yaml
# kubectl scale --replicas=6 -f replicaset_definition.yaml
# kubectl scale --replicas=6 ${type} ${name}