# /etc/kubernetes/manifests 


#   1
#
# kubelet.service
#
# ExecStart=/usr/local/bin/kubelet \\
#   --pod-manifest-path=/etc/Kubernetes/manifests \\
#
#   OR
#
#   2
#
#
# kubelet.service
#
# ExecStart=/usr/local/bin/kubelet \\
#   --pod-manifest-path=/etc/Kubernetes/manifests \\
#   --config=kubeconfig.yaml \\
#
#
# kubeconfig.yaml
# staticPodPath: /etc/kubernetes/manifests
# 
# 
#   Name: pod-name-node-name
#         static-web-node01

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: static-busybox
  name: static-busybox
spec:
  containers:
  - command:
    - sleep
    - "1000"
    image: busybox
    name: static-busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
