apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
    - name: busybox
      image: busybox