apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - targetPort: 80 # if not presented, can be the same as port
      port: 80 # mandatory
  selector: # Pod's labels from metadata
    app: myapp
    type: back-end