apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  volumes:
    - name: config-volume
      configMap:
        name: app-config
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    volumeMounts:
    - name: config-volume
      subPath: config.yml
      mountPath: "/home/app/config.yml"