apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  volumes:
    - name: config-volume
      secret:
        secretName: app-secret
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color



# ls /opt/app-secret-volumes
# DB_Host    DB_Password    DB_User
#
# cat /opt/app-secret-volumes/DB_Password
# paswrd