apiVersion: certificates.k8s.io/v1beta1
kind: CertificateesSigningRequest
metadata:
  name: jane
spec:
  groups:
    - system:authenticated
  usages:
    - difital signature
    - key encipherment
    - server auth
  request: