apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
  - apiGroups: [""]
    resouces: ["pods"]
    verbs: ["list","get","create","update","delete"]
    resourceNames: ["blue", "orange"]
  - apiGroups: [""]
    resouces: ["ConfigMap"]
    verbs: ["create"]

